# Generated by Django 5.0.8 on 2024-10-04 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0002_remove_agent_first_name_remove_agent_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='description',
            field=models.TextField(default='This Lead was created before description was required'),
        ),
    ]
