# Generated by Django 4.0 on 2024-10-10 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0007_lead_organisation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lead',
            name='description',
        ),
        migrations.AlterField(
            model_name='lead',
            name='age',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='lead',
            name='last_name',
            field=models.CharField(max_length=20),
        ),
    ]
